name: Run tests

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  test:

    runs-on: ubuntu-latest
    timeout-minutes: 30
    # runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-18.04]
        # python: ["3.8", "3.9", "3.10", "3.11"]
        python: ["3.10"]

    steps:
      - uses: actions/checkout@v4    
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      # PNPM stuff
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install node dependencies
        run: pnpm install --filter @lmkapp/jupyter-widget...

      # Python stuff
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "STORE_PATH=$(venv/bin/pip cache dir)"
      - name: Setup python cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache.outputs.STORE_PATH }} ./packages/python-client/.tox
          key: ${{ runner.os }}-python-${{ matrix.python }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-python-
      - name: Install Python dependencies
        run: |
          cd ./packages/python-client
          pnpm generate
          python -m venv venv
          . venv/bin/activate
          pip install -e '.[dev]'
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      - name: Run tests
        working-directory: ./packages/python-client
        env:
          LMK_ACCESS_TOKEN: ${{ secrets.LMK_ACCESS_TOKEN }}
          LMK_REFRESH_TOKEN: ${{ secrets.LMK_REFRESH_TOKEN }}
          LMK_ACCESS_TOKEN_EXPIRES: ${{ secrets.LMK_ACCESS_TOKEN_EXPIRES }}
        run: venv/bin/tox -e type,test-nb7-lab4,test-nb6-lab3
